# Utilise une image officielle PHP avec les extensions nécessaires
FROM php:8.2-fpm

# Installe les dépendances système
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libpq-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libmcrypt-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    libicu-dev \
    libxslt1-dev \
    libreadline-dev \
    libedit-dev \
    libsqlite3-dev \
    libmagickwand-dev \
    libmagickcore-dev \
    libmagick++-dev \
    libwebp-dev \
    libxpm-dev \
    libvpx-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libjpeg62-turbo \
    libjpeg-dev \